sources/app/routes/index.py
from flask import Blueprint, render_template

index_bp = Blueprint('index', __name__)

@index_bp.route('/')
def index():
    return render_template('index.html')


@index_bp.route('/about', methods=['GET'])
def about():
    return render_template('about.html')


@index_bp.route('/help', methods=['GET'])
def help():
    return render_template('help.html')


@index_bp.route('/tips', methods=['GET'])
def tips():
    return render_template('tips.html')


@index_bp.route('/law', methods=['GET'])
def law():
    return render_template('law.html')

sources/app/routes/upload.py
from flask import Blueprint, render_template, request,jsonify, redirect, Response
from werkzeug.utils import secure_filename
import base64, os, secrets, numpy as np
# import cv2
from flask import current_app

from app.models.img_process import process_image
from datetime import datetime

upload_bp = Blueprint('upload', __name__)

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@upload_bp.route('/upload', methods=['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        if 'file' not in request.files:
            return 'No file part'

        file = request.files['file']

        if file.filename == '':
            return redirect(request.url) 

        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            current_time = datetime.now().strftime("%Y-%m-%d_%H%M%S")


            random_string = secrets.token_hex(8)
            new_filename = current_time + '_' + random_string + '_' + filename

            # Lấy đường dẫn tuyệt đối của file hiện tại
            folder_name = '/static/uploads'
            root_path = current_app.root_path
            
            absolute_path = root_path + folder_name

            file.save(os.path.join(absolute_path, new_filename))
            
            # Gọi model AI để xử lý ảnh
            num_res = process_image(new_filename)

            str_res = transfer_lable(num_res)
            return jsonify({'result': str_res})
    
    return render_template('upload.html')


def transfer_lable(index):
    strings_list = ['battery', 'biological', 'brown-glass', 'cardboard', 'clothes', 'green-glass', 'metal', 'paper', 'plastic', 'shoes', 'trash', 'white-glass']
    return strings_list[index]


@upload_bp.route('/upload_from_camera', methods=['GET'])
def show_upload_from_camera():
    return render_template('capture_image.html')

@upload_bp.route('/upload_from_camera', methods=['POST'])
def upload_from_camera():
    data = request.get_json()
    if 'image' in data:
        image_data = data['image'].split(',')[1]  # Lấy dữ liệu ảnh từ base64
        img_data = base64.b64decode(image_data)
        
        # Lưu ảnh vào thư mục UPLOAD_FOLDER
        current_time = datetime.now().strftime("%Y-%m-%d_%H%M%S")
        random_string = secrets.token_hex(8)
        new_filename = 'camera_image' + '_' + current_time + '_' + random_string + '.jpg'
        
        # Lấy đường dẫn tuyệt đối của file hiện tại
        folder_name = '/static/uploads'
        root_path = current_app.root_path
        absolute_path = root_path + folder_name
        
        with open(os.path.join(absolute_path, new_filename), 'wb') as f:
            f.write(img_data)

        # Xử lý ảnh (nếu cần)

        #Gọi Modek AI
        num_res = process_image(new_filename)
        str_res = transfer_lable(num_res)
        return jsonify({'result': str_res})
        
    return 'Invalid request'


# @upload_bp.route('/detect_objects')
# def video_feed():
#     return Response(detect_objects(), mimetype='multipart/x-mixed-replace; boundary=frame')


# def detect_objects():
#     camera = cv2.VideoCapture(0) 
#     net = cv2.dnn.readNet("yolov3.weights", "yolov3.cfg")
#     classes = []
#     with open("coco.names", "r") as f:
#         classes = [line.strip() for line in f.readlines()]

#     layer_names = net.getLayerNames()
#     output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
#     print(output_layers)

#     while True:
#         success, frame = camera.read()
#         if not success:
#             break

#         height, width, channels = frame.shape
#         blob = cv2.dnn.blobFromImage(frame, 0.00392, (416, 416), (0, 0, 0), True, crop=False)
        
#         net.setInput(blob)
#         outs = net.forward(output_layers)
        
#         class_ids = []
#         confidences = []
#         boxes = []
        
#         for out in outs:
#             for detection in out:
#                 scores = detection[5:]
#                 class_id = np.argmax(scores)
#                 confidence = scores[class_id]
#                 if confidence > 0.5:
#                     center_x = int(detection[0] * width)
#                     center_y = int(detection[1] * height)
#                     w = int(detection[2] * width)
#                     h = int(detection[3] * height)

#                     x = int(center_x - w / 2)
#                     y = int(center_y - h / 2)

#                     boxes.append([x, y, w, h])
#                     confidences.append(float(confidence))
#                     class_ids.append(class_id)
        
#         indexes = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, 0.4)
        
#         for i in range(len(boxes)):
#             if i in indexes:
#                 x, y, w, h = boxes[i]
#                 label = str(classes[class_ids[i]])
#                 cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)
#                 cv2.putText(frame, label, (x, y + 30), cv2.FONT_HERSHEY_PLAIN, 3, (0, 255, 0), 3)

#         ret, buffer = cv2.imencode('.jpg', frame)
#         frame = buffer.tobytes()
#         yield (b'--frame\r\n'
#                b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

sources/app/routes/version.py
from flask import Blueprint, render_template, request, redirect, url_for
import os
from flask import current_app
from dotenv import set_key, dotenv_values
from app.repositories.auth import User
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user


version_bp = Blueprint('version', __name__)

@version_bp.route('/load-version', methods=['GET', 'POST'])
@login_required
def load_version():
    list_files = get_list_files()
    current_ver = get_current_version()
    if request.method == "POST":
        if 'file' not in request.files:
            return 'No file part'

        file = request.files['file']

        if file.filename == '':
            return redirect(request.url) 

        if file:
            folder_name = '/models/files'
            root_path = current_app.root_path
            absolute_path = root_path + folder_name
            file.save(os.path.join(absolute_path, file.filename))
            return redirect(request.url) 
        
    return render_template('version.html', files=list_files, ver = current_ver)


@version_bp.route('/pick-version', methods=[ 'POST'])
@login_required
def pick_version():
    if request.method == 'POST':
        if 'version_model' in request.form and request.form['version_model'] is not None:
            model_name = request.form['version_model']     
            set_key('.env', 'VER', model_name)

    return redirect(url_for('version.load_version')) 


def get_current_version():
    env_vars = dotenv_values('.env')
    return env_vars.get('VER')


def get_list_files():
    folder_name = '/models/files'
    root_path = current_app.root_path
    absolute_path = root_path + folder_name
    if os.path.exists(absolute_path) and os.path.isdir(absolute_path):
        files = os.listdir(absolute_path)
        return files
    else:
        return 'Folder not found or is not a directory'

sources/app/templates/about.html
{% extends 'layout.html' %}

{% block title %}About Us{% endblock %}

{% block content %}
<div class="nav-page">
    <div class="w-btn-link">
        <ul>
            <li><a href="{{ url_for('index.index') }}" title="index" rel="noopener noreferrer"><i class="fa-solid fa-house"></i></a></li>
            <li><a href="{{ url_for('index.help') }}" title="help" rel="noopener noreferrer"><i class="fa-regular fa-circle-question"></i></a></li>
            <li><a href="{{ url_for('index.about') }}" title="about" rel="noopener noreferrer"><i class="fa-solid fa-circle-info"></i></a></li>
        </ul>
    </div>
</div>

<section class="w-about">
    <h2 class="w-about-head">Les Miserables Team</h2>
    <ul>
        <li>
            <h4 class="name-user">Võ Trọng Phúc</h4>
        </li>
        <li>
            <h4 class="name-user">Ya Xê Chiên</h4>
        </li>
        <li>
            <h4 class="name-user">Nguyễn Ngọc Duy</h4>
        </li>
        <li>
            <h4 class="name-user">Trần Minh Trí</h4>
        </li>
    </ul>
</section>

<footer class="w-footer">
    <img src="{{ url_for('static', filename='imgs/aptech-logo.png') }}" alt="">
    <p>@ Copyright by Les Miserables Team </p>
</footer>

{% endblock %}

sources/app/templates/help.html
{% extends 'layout.html' %}

{% block title %}Help!{% endblock %}

{% block content %}

<div class="nav-page">
    <div class="w-btn-link">
        <ul>
            <li><a href="{{ url_for('index.index') }}" title="index" rel="noopener noreferrer"><i class="fa-solid fa-house"></i></a></li>
            <li><a href="{{ url_for('index.help') }}" title="help" rel="noopener noreferrer"><i class="fa-regular fa-circle-question"></i></a></li>
            <li><a href="{{ url_for('index.about') }}" title="about" rel="noopener noreferrer"><i class="fa-solid fa-circle-info"></i></a></li>
        </ul>
    </div>
</div>

<div class="w-help-content">
    <ul class="w-laws">
        <li><i class="fa-regular fa-bookmark"></i> <a href="{{ url_for('index.tips') }}">Tips</a></li>
        <li><i class="fa-solid fa-gavel"></i> <a href="{{ url_for('index.law') }}">Sanction regulations</a></li>
    </ul>
</div>

<footer class="w-footer">
    <img src="{{ url_for('static', filename='imgs/aptech-logo.png') }}" alt="">
    <p>@ Copyright by Les Miserables Team </p>
</footer>

{% endblock %}

sources/app/templates/law.html
{% extends 'layout.html' %}

{% block title %}Help!{% endblock %}

{% block content %}

<div class="nav-page">
    <div class="w-btn-link">
        <ul>
            <li><a href="{{ url_for('index.index') }}" title="index" rel="noopener noreferrer"><i class="fa-solid fa-house"></i></a></li>
            <li><a href="{{ url_for('index.help') }}" title="help" rel="noopener noreferrer"><i class="fa-regular fa-circle-question"></i></a></li>
            <li><a href="{{ url_for('index.about') }}" title="about" rel="noopener noreferrer"><i class="fa-solid fa-circle-info"></i></a></li>
        </ul>
    </div>
</div>

<div class="w-help-content">
    <p>Theo Bộ Tài nguyên và Môi trường, từ ngày 1/1/2025, phân loại chất thải rắn sinh hoạt là việc làm bắt buộc với mọi cá nhân và hộ gia đình. Đến thời điểm đó, nếu không thực hiện phân loại chất thải rắn sinh hoạt tại nguồn sẽ bị xử phạt vi phạm hành chính theo Nghị định số 45/2022/NĐ-CP ngày 7/7/2022 của Chính phủ quy định về xử phạt vi phạm hành chính trong lĩnh vực bảo vệ môi trường.</p>
    <p>
        Theo nghị định này, hộ gia đình, cá nhân không phân loại chất thải rắn sinh hoạt và không sử dụng bao bì chứa chất thải rắn sinh hoạt theo quy định có thể bị phạt tiền từ 500.000 - 1.000.000 đồng.
    </p>
    
    <p>
        Nghị định cũng quy định các mức xử phạt cụ thể đối với hành vi rò rỉ, thải hóa chất độc vào môi trường đất, nước; vi phạm các quy định về đưa chất thải vào lãnh thổ Việt Nam; hành vi cản trở hoạt động quản lý nhà nước, thanh tra, kiểm tra, xử phạt vi phạm hành chính về bảo vệ môi trường… Cụ thể, phạt tiền từ 100.000 đồng đến 150.000 đồng đối với hành vi vứt, thải, bỏ đầu, mẩu, tàn thuốc lá không đúng nơi quy định tại khu chung cư, thương mại, dịch vụ hoặc nơi công cộng.</p>

    <p>
        Phạt tiền từ 150.000 đồng đến 250.000 đồng đối với hành vi vệ sinh cá nhân (tiểu tiện, đại tiện) không đúng nơi quy định tại khu chung cư, thương mại, dịch vụ hoặc nơi công cộng.
    </p>

    <p>
        Phạt tiền từ 500.000 đồng đến 1.000.000 đồng đối với hành vi vứt, thải, bỏ rác thải, đổ nước thải không đúng nơi quy định tại khu chung cư, thương mại, dịch vụ hoặc nơi công cộng.
    </p>
    <p>
        Phạt tiền từ 1.000.000 đồng đến 2.000.000 đồng đối với hành vi vứt, thải, bỏ rác thải trên vỉa hè, lòng đường hoặc vào hệ thống thoát nước thải đô thị; đổ nước thải không đúng quy định trên vỉa hè, lòng đường phố; thải bỏ chất thải nhựa phát sinh từ sinh hoạt vào ao hồ, kênh rạch, sông, suối, biển…
    </p>
</div>

<footer class="w-footer">
    <img src="{{ url_for('static', filename='imgs/aptech-logo.png') }}" alt="">
    <p>@ Copyright by Les Miserables Team </p>
</footer>

{% endblock %}

sources/app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='imgs/aptech-logo.png') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

</head>
<body>
    <main>
        {% block content %}
        <!-- Nội dung của mỗi trang sẽ được hiển thị ở đây -->
        {% endblock %}
        <div id="loading">
            <div class="lds-spinner">
                {% for i in range(12) %}
                    <div></div>
                {% endfor %}
            </div>
        </div>
    </main>

    <script src="{{ url_for('static', filename='js/detect.js') }}"></script>
    
</body>
</html>

sources/app/templates/login.html
{% extends 'layout.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="wapper-login">
        <h1>Login</h1>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li class="{{ message[1] }}">{{ message[0] }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
        <form method="post" action="/login" id="form-login">
            <div class="form-row">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            
            <br>
            <div class="form-row">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <br>
            <div class="form-row f-btn-login">
                <button type="submit" id="btn-flogin">Login</button>
            </div>
        </form>

    </div>
{% endblock %}

sources/app/templates/tips.html
{% extends 'layout.html' %}

{% block title %}Help!{% endblock %}

{% block content %}

<div class="nav-page">
    <div class="w-btn-link">
        <ul>
            <li><a href="{{ url_for('index.index') }}" title="index" rel="noopener noreferrer"><i class="fa-solid fa-house"></i></a></li>
            <li><a href="{{ url_for('index.help') }}" title="help" rel="noopener noreferrer"><i class="fa-regular fa-circle-question"></i></a></li>
            <li><a href="{{ url_for('index.about') }}" title="about" rel="noopener noreferrer"><i class="fa-solid fa-circle-info"></i></a></li>
        </ul>
    </div>
</div>

<div class="w-tips-content">
    <!-- <h2>Cách phân loại rác</h2> -->
    <img src="{{ url_for('static', filename='imgs/tips.png') }}" alt="" srcset="">
</div>

<footer class="w-footer">
    <img src="{{ url_for('static', filename='imgs/aptech-logo.png') }}" alt="">
    <p>@ Copyright by Les Miserables Team </p>
</footer>

{% endblock %}

sources/app/templates/version.html
{% extends 'layout.html' %}

{% block title %}Version!{% endblock %}

{% block content %}

<div class="nav-page">
    <div class="w-btn-link">
        <ul>
            <li><a href="{{ url_for('index.index') }}" title="index" rel="noopener noreferrer"><i class="fa-solid fa-house"></i></a></li>
            <li><a href="{{ url_for('index.help') }}" title="help" rel="noopener noreferrer"><i class="fa-regular fa-circle-question"></i></a></li>
            <li><a href="{{ url_for('index.about') }}" title="about" rel="noopener noreferrer"><i class="fa-solid fa-circle-info"></i></a></li>
        </ul>
    </div>
</div>

<div class="w-help-content">
    <h3>Current Version Model : {{ ver }}</h3>
    <div class="w-upload-file">
        <form method="POST" enctype="multipart/form-data" action="/load-version">
            <input type="file" name="file">
            <button class="btn-up-model">Upload model</button>
        </form>
    </div>

    <div class="w-choose-version">
        <h3>List Version</h3>
        <form method="POST" action="/pick-version" enctype="multipart/form-data" id="sendImage">
            <ul>
                {% for file in files %}
                    <li ><input type="radio" name="version_model" value="{{file}}" id="{{file}}"><label for="{{file}}">{{ file }}</label></li>
                {% endfor %}
            </ul>
            <button class="btn-choose-model">Update version</button>
        </form>
    </div>
</div>

<footer class="w-footer">
    <img src="{{ url_for('static', filename='imgs/aptech-logo.png') }}" alt="">
    <p>@ Copyright by Les Miserables Team </p>
</footer>


{% endblock %}